# Basic Data Exploration and Cleaning using Pandas

## Celebal Technologies Internship Assignment

### Objective
To perform data exploration and cleaning using Pandas.

In [1]:
import pandas as pd
import numpy as np

## Loading Dataset

In [2]:
df = pd.read_csv("clothing-set.csv")

## Display First 5 Rows

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

## Display Last 5 Rows

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",NaN,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",NaN,"A-2███, T███D F█████████ -1█████████████████████8",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",NaN,"146███LAK███OWN█████████, 2███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

## Shape of Dataset

## Shape of Dataset

In [5]:
df.shape

(2, 24)

## Column Names

In [6]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

## Dataset Information

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2 non-null      int64
 1   title                   2 non-null      object
 2   product_description     2 non-null      object
 3   rating                  2 non-null      float64
 4   ratings_count           2 non-null      int64
 5   initial_price           2 non-null      float64
 6   discount                2 non-null      float64
 7   final_price             2 non-null      object
 8   currency                2 non-null      object
 9   images                  2 non-null      object
 10  delivery_options        2 non-null      object
 11  product_details         2 non-null      object
 12  breadcrumbs             2 non-null      object
 13  product_specifications  2 non-null      object
 14  amount_of_stars         2 non-null      object
 15  what_customers_said     0 non-null      float64
 16  seller_name             2 non-null      object
 17  sizes                   2 non-null      object
 18  videos                  0 non-null      float64
 19  seller_information      2 non-null      object
 20  variations              0 non-null      float64
 21  best_offer              2 non-null      object
 22  more_offers             2 non-null      object
 23  category                2 non-null      object
dtypes: float64(6), int64(2), object(16)
memory usage: 512.0+ bytes

## Statistical Summary

In [8]:
df.describe()

,product_id,rating,ratings_count,initial_price,discount,what_customers_said,videos,variations
count,2.000000e+00,2.000000,2.000000,2.000000,2.000000,0.0,0.0,0.0
mean,1.927460e+07,4.300000,233.500000,1224.000000,50.000000,NaN,NaN,NaN
std,3.622654e+06,0.282843,311.834091,1096.015511,28.284271,NaN,NaN,NaN
min,1.671299e+07,4.100000,13.000000,449.000000,30.000000,NaN,NaN,NaN
25%,1.799379e+07,4.200000,123.250000,836.500000,40.000000,NaN,NaN,NaN
50%,1.927460e+07,4.300000,233.500000,1224.000000,50.000000,NaN,NaN,NaN
75%,2.055540e+07,4.400000,343.750000,1611.500000,60.000000,NaN,NaN,NaN
max,2.183620e+07,4.500000,454.000000,1999.000000,70.000000,NaN,NaN,NaN

## Checking Missing Values

In [9]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       2
seller_name               0
sizes                     0
videos                    2
seller_information        0
variations                2
best_offer                0
more_offers               0
category                  0
dtype: int64

## Handling Missing Values

In [10]:
df.fillna("Not Available", inplace=True)

C:\Users\Harish\AppData\Local\Temp\ipykernel_16380\3513367982.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("Not Available", inplace=True)

In [11]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

## Checking Duplicate Values

In [12]:
df.duplicated().sum()

0

## Filtering Rows

In [13]:
df[df["rating"] > 4]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":43,""2_stars"":14,""3_stars"":50,""4_star...",Not Available,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",Not Available,"A-2███, T███D F█████████ -1█████████████████████8",Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,"""₹314.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",Not Available,"146███LAK███OWN█████████, 2███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set

## Selecting Specific Columns

In [14]:
df[["title", "rating", "final_price"]]

           title  rating final_price
0      Cutiekins     4.1   "₹719.00"
1  Nottie Planet     4.5   "₹314.00"

## Creating Quantity Column

In [15]:
df["quantity"] = np.random.randint(1, 6, size=len(df))

## Cleaning Price Column

In [16]:
df["final_price"] = (
    df["final_price"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False)
    .astype(float)
)

In [17]:
df["final_price"].dtype

dtype('float64')

## Creating Derived Column

In [18]:
df["total_amount"] = df["final_price"] * df["quantity"]

## Updated Dataset

In [19]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,16712992,Cutiekins,Girls Pink & White Printed Top with Shorts,4.1,454,1999.0,70.0,719.0,INR,http://assets.myntassets.com/assets/images/167...,...,CUT███INS███IVA█████████D,"[{""size"":""4-5Y"",""value"":""25.0in"",""value_name"":...",Not Available,"A-2███, T███D F█████████ -1█████████████████████8",Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set,2,1438.0
1,21836198,Nottie Planet,Boys Printed T-shirt with Shorts,4.5,13,449.0,30.0,314.0,INR,http://assets.myntassets.com/assets/images/218...,...,MOO███ FA███ONS█████████,"[{""size"":""12-18M"",""value"":""20.0in"",""value_name...",Not Available,"146███LAK███OWN█████████, 2███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",clothing-set,1,314.0

In [20]:
df.to_csv("cleaned_shopping_data.csv", index=False)

# Summary

- Loaded dataset using Pandas
- Explored dataset structure using head(), tail(), shape, columns and info()
- Checked and handled missing values
- Removed duplicate values
- Filtered rows and selected columns
- Created quantity column
- Cleaned price column
- Created derived column total_amount
- Saved cleaned dataset as CSV